### ISSUE TITLE
Train custom data depth (z-axis) smaller than patch size 96

### ISSUE THREAD

**Issue by kmin940** [XuzheZ/MAPSeg#3]
Thank you for your amazing work! I am trying to train on a custom dataset, and successfully trained MAE model. However, during MPL training, I am getting the following error as the depth is less than the patch size.
```
Traceback (most recent call last):
  File "/home/sumin2/Documents/MAPSeg/train.py", line 128, in <module>
    save_best = train_solver.validation(epoch)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/Documents/MAPSeg/model/solver.py", line 493, in validation
    tmp_pred = self.infer_single_scan(tmp_scans)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/miniconda3/envs/mapseg/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/Documents/MAPSeg/model/solver.py", line 405, in infer_single_scan
    scan_patches, _, tmp_idx = util.patch_slicer(tmp_scans, tmp_scans, self.cfg.data.patch_size,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sumin2/Documents/MAPSeg/model/utils/util.py", line 243, in patch_slicer
    for z_idx in z_steps:
  File "/home/sumin2/Documents/MAPSeg/model/utils/util.py", line 180, in _gen_indices
    assert i2 >= k, f'sample size {i2} has to be bigger than the patch size {k}'
           ^^^^^^^
AssertionError: sample size 72 has to be bigger than the patch size 96
```
May I ask how I can resolve this? 

Thank you very much.

**Comment by XuzheZ** [comment]
Hi! Thank you for raising this issue! There is a bug in dataloader that can't appropriately handle the situation where there is more than one dimension is smaller than the patch size (e.g., both x and y are smaller than the patch size). I've pushed an update, and feel free to try after pulling the update. Please reopen the issue and let me know if you encounter other problems! 

Best,
Xuzhe
